local E = {
    ID = "whittagann_dal",
    Base = "base",
    Name = "Whittagann Exterior",
    Category = "DALLIIAS",
		Model="models/dalliias/whittagann/exterior/exterior_c.mdl",
		Mass=2900,
		ScannerOffset=Vector(30,0,50),
Portal = {
	-- Generated by portals debug tool
	pos = Vector(28.013013839722, -0.01, 48.6904296875),
	ang = Angle(-0, 0, 0),
	width = 44,
	height = 95,
	thickness = 41,
	inverted = true,
},

	Fallback={
		pos=Vector(55,0,5),
		ang=Angle(0,0,0)
	},
	Light={
		enabled=true,
		pos=Vector(0, 0, 116),
		color=Color(200,155,155)
	},
	Sounds={
		Teleport={
			demat="flight/demat.wav",
			mat="flight/mat.wav",
		},
		FlightLoop="flight/interior_flight.wav"
	},

Parts={
	door={
		model="models/dalliias/whittagann/exterior/doorsext.mdl",
		posoffset=Vector(-28.013013839722,00,-48.6904296875),
		angoffset = Angle(0,0,0)
	}
},
Teleport={
		SequenceSpeed=0.75,
		SequenceSpeedFast=1,
		DematSequenceDelays={
			[2] = 1
			},
		DematSequence={
			150,
			200,
			100,
			150,
			50,
			100,
			0
		},
		MatSequence={
			150,
			100,
			200,
			150,
			255
		    }
      }
    }

 

TARDIS:AddExterior(E)